name: Unit Test (with coverage)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-test-coverage:
    runs-on: ubuntu-latest
    outputs:
      code_coverage: ${{ steps.coverage_in_percentage.outputs.coverage_as_str }}
      code_coverage_as_int: ${{ steps.coverage_in_percentage.outputs.coverage_as_int }}
    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-tarpaulin from crates.io
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-tarpaulin
        version: "0.25.2"
    - name: Run tests with coverage
      run: |
        cargo tarpaulin --out Xml
    - id: coverage_in_percentage
      run: |
        COVERAGE=$(cat cobertura.xml | grep -oP '(?<=line-rate=").*(?=" branches-covered)')
        CODE_COVERAGE_AS_STR=$(echo "scale=2; ($COVERAGE * 100)" | bc | xargs printf "%.2f")
        CODE_COVERAGE_AS_INT=${CODE_COVERAGE_AS_STR%.*}
        echo "coverage_as_str=${CODE_COVERAGE_AS_STR}" >> "$GITHUB_OUTPUT"
        echo "coverage_as_int=${CODE_COVERAGE_AS_INT}" >> "$GITHUB_OUTPUT"
  calculate-coverage-percentage:
    runs-on: ubuntu-latest
    needs: unit-test-coverage
    outputs:
      code_coverage_percentage: ${{ steps.percentage.outputs.percentage }}
      code_coverage_percentage_as_int: ${{ steps.percentage.outputs.percentage_as_int }}
    steps:
    - id: percentage
      run: |
        COVERAGE_IN_PERCENTAGE=${{needs.unit-test-coverage.outputs.code_coverage}}
        COVERAGE_IN_PERCENTAGE_AS_INT=${{needs.unit-test-coverage.outputs.code_coverage_as_int}}
        echo "percentage=${COVERAGE_IN_PERCENTAGE}" >> "$GITHUB_OUTPUT"
        echo "percentage_as_int=${COVERAGE_IN_PERCENTAGE_AS_INT}" >> "$GITHUB_OUTPUT"
  create-coverage-badge:
    runs-on: ubuntu-latest
    needs: calculate-coverage-percentage
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          path: badges
          persist-credentials: false
          fetch-depth: 0
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v1
        id: badge
        with:
          label: 'Code Coverage'
          status: ${{ needs.calculate-coverage-percentage.outputs.code_coverage_percentage }}%
          color: ${{
            needs.calculate-coverage-percentage.outputs.code_coverage_percentage_as_int > 90 && 'green'              ||
            needs.calculate-coverage-percentage.outputs.code_coverage_percentage_as_int > 80 && 'yellow,green'       ||
            needs.calculate-coverage-percentage.outputs.code_coverage_percentage_as_int > 70 && 'yellow'             ||
            needs.calculate-coverage-percentage.outputs.code_coverage_percentage_as_int > 60 && 'orange,yellow'      ||
            needs.calculate-coverage-percentage.outputs.code_coverage_percentage_as_int > 50 && 'orange'             ||
            needs.calculate-coverage-percentage.outputs.code_coverage_percentage_as_int > 40 && 'red,orange'         ||
            needs.calculate-coverage-percentage.outputs.code_coverage_percentage_as_int > 30 && 'red,red,orange'     ||
            needs.calculate-coverage-percentage.outputs.code_coverage_percentage_as_int > 20 && 'red,red,red,orange' ||
            'red' }}
          path: badges/test-coverage.svg
      - name: Commit badge
        env:
          FILE: 'test-coverage.svg'
        working-directory: ./badges
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          mkdir -p main
          mv test-coverage.svg main
          git add main/test-coverage.svg
          git commit -a -m "Add changes" || true
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: badges
