name: Unit Test (with coverage)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-tarpaulin from crates.io
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-tarpaulin
        version: "0.25.2"
    - name: Run tests with coverage
      run: cargo tarpaulin --out Xml
    - name: Generate a coverage value
      id: coverage
      # Generates a GitHub Workflow output named `lines`
      run: |
        COVERAGE="$( cobertura.xml )"
        echo "##[set-output name=lines;]${COVERAGE}%"

      # Use the output from the `coverage` step
    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v1
      with:
        label: 'Test coverage'
        status: ${{ steps.coverage.outputs.lines }}
        color: 'blue,555,daf'
        path: badges/test-coverage.svg
