name: Unit Test (with coverage)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-test-coverage:
    runs-on: ubuntu-latest
    outputs:
      code_coverage: ${{ steps.coverage_in_percentage.outputs.coverage }}
    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-tarpaulin from crates.io
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-tarpaulin
        version: "0.25.2"
    - name: Run tests with coverage
      run: |
        cargo tarpaulin --out Xml
    - id: coverage_in_percentage
      run: |
        COVERAGE=$(( $(cat cobertura.xml | grep -oP '(?<=line-rate=").*(?=" branches-covered)') ))
        echo "coverage=${COVERAGE}" >> "$GITHUB_OUTPUT"
  calculate-coverage-percentage:
    runs-on: ubuntu-latest
    needs: unit-test-coverage
    steps:
      - env:
          COVERAGE_IN_PERCENTAGE: ${{needs.unit-test-coverage.outputs.code_coverage}}
        run: echo $(( $COVERAGE_IN_PERCENTAGE * 100))
