name: Unit Test (with coverage)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-tarpaulin from crates.io
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-tarpaulin
        version: "0.25.2"
    - name: Run tests with coverage
      run: |
        cargo tarpaulin --out Xml
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: code_coverage_report
        path: cobertura.xml
  getting-coverage-report:
    runs-on: ubuntu-latest
    needs: unit-test-coverage
    outputs:
      output1: ${{ steps.lines-valid.outputs.info }}
      output2: ${{ steps.lines-covered.outputs.info }}
      output3: ${{ steps.lines-covered.outputs.info}} / ${{ steps.lines-valid.outputs.info }} * 100
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: code_coverage_report
      - name: Get coverage (lines valid)
        id: lines-valid
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'cobertura.xml'
          xpath: '//coverage.lines-valid'
      - name: Get coverage (lines covered)
        id: lines-covered
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'cobertura.xml'
          xpath: '//coverage.lines-covered'
  calculate-coverage-percentage:
    runs-on: ubuntu-latest
    needs: getting-coverage-report
    steps:
      - env:
          COVERAGE_IN_PERCENTAGE: ${{needs.getting-coverage-report.outputs.output3}}
        run: echo "$COVERAGE_IN_PERCENTAGE"
