name: Unit Test (with coverage)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-test-coverage:
    runs-on: ubuntu-latest
    outputs:
      code_coverage: ${{ steps.coverage_in_percentage.outputs.coverage }}
    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-tarpaulin from crates.io
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-tarpaulin
        version: "0.25.2"
    - name: Run tests with coverage
      run: |
        cargo tarpaulin --out Xml
    - id: coverage_in_percentage
      run: |
        COVERAGE=$(cat cobertura.xml | grep -oP '(?<=line-rate=").*(?=" branches-covered)')
        CODE_COVERAGE=$(echo "scale=2; ($COVERAGE * 100)" | bc | xargs printf "%.2f")
        echo "coverage=${CODE_COVERAGE}" >> "$GITHUB_OUTPUT"
  calculate-coverage-percentage:
    runs-on: ubuntu-latest
    needs: unit-test-coverage
    outputs:
      code_coverage_percentage: ${{ steps.percentage.outputs.percentage }}
    steps:
    - id: percentage
      run: |
        COVERAGE_IN_PERCENTAGE=${{needs.unit-test-coverage.outputs.code_coverage}}
        echo "percentage=${COVERAGE_IN_PERCENTAGE}%" >> "$GITHUB_OUTPUT"
  create-coverage-badge:
    runs-on: ubuntu-latest
    needs: calculate-coverage-percentage
    steps:
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v1
        with:
          label: 'Test coverage'
          status: ${{ needs.calculate-coverage-percentage.outputs.code_coverage_percentage }}
          color: 'blue,555,daf'
          path: ${{ github.workspace }}/.github/badges/test-coverage.svg
