name: Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-tarpaulin from crates.io
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-tarpaulin
        version: "0.25.2"
    - name: Run tests with coverage
      run: cargo tarpaulin
